### ISSUE TITLE
How to visualize the scene (.pcd) file?

### ISSUE THREAD

**Issue by herohuyongtao** [climbingdaily/HSC4D#1]
How to visualize the scene (.pcd) file in the dataset?

**Comment by climbingdaily** [comment]
Hi Yongtao, 

Our visualization code and sample data are about to release in two weeks, you can refer "vis_double.py" in this codebase 
https://github.com/climbingdaily/vis_lidar_human_scene  to visualize the scene.

**Comment by herohuyongtao** [comment]
Thanks @climbingdaily for the update. Currently I am using CloudCompare to vis the data, and it works good for now.

**Comment by herohuyongtao** [comment]
Thanks @climbingdaily for the update. Currently I am using CloudCompare to vis the data, and it works good for now.
